### ISSUE TITLE
bug，记录按钮显示不出来

### ISSUE THREAD

**Issue by apanese** [frostime/sy-time-logger#23]
![image](https://github.com/user-attachments/assets/79bacc7a-1c45-41b8-bab9-8bb50f436d72)
如图所示，这是bug还是我不会用？找不到打开计时器的按钮

**Comment by frostime** [comment]
你打开的是配置页面。

主页面的按钮在侧栏：
![image](https://github.com/user-attachments/assets/f8f3f912-da7c-4a6a-befa-a001cbf8ba80)

**Comment by apanese** [comment]
谢谢谢，已经找到了！可以考虑下在插件安装页面写上使用提示，不然可能会有其他新用户像我一样蒙头找不到入口~
